load("//build:macros.bzl", "go_lib", "go_test_lib")

go_lib(
    name = "http",
    srcs = ["http.go"],
    importpath = "github.com/ecommerce/libs/go/http",
    tags = ["type=utility"],
    visibility = ["//teams:public"],
)

go_test_lib(
    name = "http_test",
    size = "small",
    srcs = ["http_test.go"],
    embed = [":http"],
)
